// CV Data for Ruslan Pavlenko - All versions
const cvData = {
  personal: {
    name: { en: "Ruslan Pavlenko", de: "Ruslan Pavlenko", ua: "Руслан Павленко" },
    photo: "assets/images/photo.jpg",
    location: "44263, Dortmund, Germany",
    phone: "+38 067 483 22 43",
    email: "pavlenko.rv@gmail.com",
    linkedin: "linkedin.com/in/pavlenko-rv",
    linkedinUrl: "https://linkedin.com/in/pavlenko-rv",
  },

  languages: {
    en: [
      { lang: "🇩🇪 German",    level: "B2 – Upper-Intermediate" },
      { lang: "🇬🇧 English",   level: "B2 – Upper-Intermediate" },
      { lang: "🇺🇦 Ukrainian", level: "C2 – Native" },
      { lang: "russian",       level: "C2 – Native" },
    ],
    de: [
      { lang: "🇩🇪 Deutsch",    level: "B2 – Oberstufe" },
      { lang: "🇬🇧 Englisch",   level: "B2 – Oberstufe" },
      { lang: "🇺🇦 Ukrainisch", level: "C2 – Muttersprache" },
      { lang: "russisch",       level: "C2 – Muttersprache" },
    ],
    ua: [
      { lang: "🇩🇪 Німецька",   level: "B2 – Вище середнього" },
      { lang: "🇬🇧 Англійська", level: "B2 – Вище середнього" },
      { lang: "🇺🇦 Українська", level: "C2 – Рідна" },
      { lang: "російська",      level: "C2 – Вільне володіння" },
    ],
  },

  education: {
    en: [
      { years: "1991–1998", degree: "Diploma Engineer, Automation of Technological Processes", institution: "Odesa Polytechnic University" },
      { years: "1999–2001", degree: "Diploma Engineer, Computer Systems", institution: "Odesa State Environmental University" },
      { years: "2005–2007", degree: "Engineer-Educator", institution: "Kharkiv Institute of Advanced Education" },
      { years: "2005–2007", degree: "International Engineering Educator (ING-PAED IGIP)", institution: "IGIP – Vienna, Austria" },
      { years: "2020", degree: "HR Director Course", institution: "LABA Kyiv" },
      { years: "2021", degree: "Product Manager Course", institution: "LABA Kyiv" },
    ],
    de: [
      { years: "1991–1998", degree: "Diplom-Ingenieur, Automatisierung technologischer Prozesse", institution: "Odesa Polytechnische Universität" },
      { years: "1999–2001", degree: "Diplom-Ingenieur, Computersysteme", institution: "Odesa Staatliche Umweltuniversität" },
      { years: "2005–2007", degree: "Ingenieur-Pädagoge", institution: "Charkiwer Institut für Weiterbildung" },
      { years: "2005–2007", degree: "International Engineering Educator (ING-PAED IGIP)", institution: "IGIP – Wien, Österreich" },
      { years: "2020", degree: "HR-Direktor-Kurs", institution: "LABA Kyjiw" },
      { years: "2021", degree: "Produktmanager-Kurs", institution: "LABA Kyjiw" },
    ],
    ua: [
      { years: "1991–1998", degree: "Інженер з автоматизації технологічних процесів та виробництв", institution: "Одеський політехнічний університет" },
      { years: "1999–2001", degree: "Інженер комп'ютерних систем та мереж", institution: "Одеський державний екологічний університет" },
      { years: "2005–2007", degree: "Інженер-педагог", institution: "Харківський інститут підвищення кваліфікації" },
      { years: "2005–2007", degree: "Міжнародний інженер-викладач (ING-PAED IGIP)", institution: "IGIP – Відень, Австрія" },
      { years: "2020", degree: "Курс HR-директора", institution: "LABA Київ" },
      { years: "2021", degree: "Курс продуктового менеджера", institution: "LABA Київ" },
    ],
  },

  pm: {
    en: {
      title: "Project Manager | Product Manager | Business & IT Strategy Leader",
      summary: "Experienced Project/Product Manager with over 20 years in IT, Education/EdTech, and digital innovation. Skilled in leading cross-functional teams, delivering successful digital products, and aligning project outcomes with business goals. Proven record of managing the full product lifecycle — from discovery and MVP to scale — as well as driving Agile transformations and optimizing delivery pipelines.",
      seeking: "Seeking mid-to-senior Project or Product Manager roles in dynamic environments focused on IT services, SaaS, AI, digital transformation, or product innovation. Available for onsite/hybrid in NRW (Dortmund area) or remote roles across Germany. Open to both product- and delivery-oriented projects.",
      experience: [
        {
          title: "IT-Director",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Kyiv, Ukraine",
          period: "Sep 2023 – Jan 2024",
          items: [
            "Acted as Product Owner for B2B energy tech platform, translating business needs into user stories.",
            "Defined product roadmap for solar power monitoring and control platform.",
            "Collaborated with development teams to iterate and deliver functional modules.",
            "Ensured stakeholder alignment and timely delivery of tech solutions.",
          ],
        },
        {
          title: "Service Member",
          company: "Territorial Defense Forces (TRO)",
          location: "Ukraine",
          period: "Feb 2022 – Sep 2023",
          items: [
            "Served in the Kyiv Territorial Defense Forces, contributing to national security during a critical period.",
            "Gained valuable experience in discipline, teamwork, and crisis management.",
          ],
        },
        {
          title: "Chief Operating Officer / Project Lead",
          company: "IT Outsourcing Company",
          location: "Tallinn, Estonia",
          period: "Nov 2013 – Dec 2023",
          items: [
            "Supervised multiple international software projects from concept to launch.",
            "Built productized service offerings and delivery pipelines using Agile frameworks.",
            "Coordinated distributed dev teams and clients across multiple time zones.",
            "Handled backlog prioritization, project scope, timelines, and cross-functional communication.",
          ],
        },
        {
          title: "Branch Director / EdTech Product Manager",
          company: 'Computer Academy "STEP"',
          location: "Zaporizhzhia, Ukraine",
          period: "Jul 2002 – Aug 2020",
          items: [
            "Led Education/EdTech product strategy: from curriculum design to platform delivery.",
            "Built partnerships with Microsoft, Cisco, Autodesk for certified learning modules.",
            "Implemented blended learning platforms and CRM-driven enrollment tracking.",
            "Oversaw operational and instructional design workflows.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45% YoY Revenue Growth", detail: "Via process optimization and scalable delivery" },
        { icon: "👥", label: "75–125 People", detail: "Led cross-functional teams with <2% turnover" },
        { icon: "🚀", label: "10+ Digital Products", detail: "Delivered across EdTech, SaaS, and Energy domains" },
        { icon: "⚙️", label: "−30% Operational Inefficiencies", detail: "Through automation of key processes" },
        { icon: "🔄", label: "Agile Transformation", detail: "Successfully implemented across departments" },
        { icon: "🤝", label: "Stakeholder Trust", detail: "High satisfaction and retention rates" },
      ],
      skillGroups: [
        { title: "Project & Product Management", skills: ["Agile", "Scrum", "Kanban", "Waterfall", "PLM", "MVP Development", "Backlog Grooming", "Requirements Gathering", "Stakeholder Alignment", "Risk Management", "Roadmapping", "OKRs", "KPIs", "Team Leadership"] },
        { title: "PM Tools", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Data & Analytics", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Marketing & Automation", skills: ["Google Ads", "Facebook Ads", "Zapier", "MailChimp", "GetResponse"] },
        { title: "Docs & Communication", skills: ["Microsoft Office", "Google Workspace", "Notion", "Confluence", "Miro", "Slack", "MS Teams"] },
        { title: "Technical Fundamentals", skills: ["HTML/CSS", "JavaScript (basics)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Stakeholder Communication", "Team Facilitation", "Conflict Resolution", "Strategic Thinking", "Data-Driven Decision Making", "Prioritization", "Roadmap Planning", "Empathy-Driven Product Development", "Active Listening", "Time & Resource Management"],
    },

    de: {
      title: "Projektmanager | Produktmanager | Leiter der Geschäfts- und IT-Strategie",
      summary: "Erfahrener Projekt- und Produktmanager mit über 20 Jahren Erfahrung in IT, Bildung/EdTech und digitaler Innovation. Leitung von funktionsübergreifenden Teams, erfolgreiche Umsetzung digitaler Produkte und Ausrichtung von Projektergebnissen an den Geschäftszielen. Nachgewiesene Erfolge im Management des gesamten Produktlebenszyklus – von der Ideenfindung und dem MVP bis zur Skalierung.",
      seeking: "Ich suche eine Position als Projekt- oder Produktmanager (Mid- bis Senior-Level) in einem dynamischen Umfeld mit Fokus auf IT-Dienstleistungen, SaaS, KI, digitale Transformation oder Produktinnovation. Verfügbar für Vor-Ort- oder Hybridarbeit in NRW (Raum Dortmund) oder für Remote-Stellen in ganz Deutschland.",
      experience: [
        {
          title: "IT-Direktor",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Kyjiw, Ukraine",
          period: "Sep 2023 – Jan 2024",
          items: [
            "Als Product Owner für eine B2B-Energietechnologie-Plattform tätig, Geschäftsanforderungen in User Stories übersetzt.",
            "Produkt-Roadmap für eine Plattform zur Überwachung und Steuerung von Solaranlagen definiert.",
            "Mit Entwicklungsteams zusammengearbeitet, um funktionale Module schrittweise zu liefern.",
            "Abstimmung mit Stakeholdern sichergestellt und pünktliche Lieferung technischer Lösungen gewährleistet.",
          ],
        },
        {
          title: "Soldat",
          company: "Territorialverteidigungskräfte (TRO)",
          location: "Ukraine",
          period: "Feb 2022 – Sep 2023",
          items: [
            "In den Territorialverteidigungskräften von Kiew gedient und zur nationalen Sicherheit beigetragen.",
            "Wichtige Erfahrungen in Disziplin, Teamarbeit und Krisenmanagement gesammelt.",
          ],
        },
        {
          title: "Chief Operating Officer / Projektleiter",
          company: "IT-Outsourcing-Unternehmen",
          location: "Tallinn, Estland",
          period: "Nov 2013 – Dez 2023",
          items: [
            "Mehrere internationale Softwareprojekte von der Idee bis zur Einführung geleitet.",
            "Standardisierte Serviceangebote und Lieferprozesse auf Basis agiler Methoden aufgebaut.",
            "Verteilte Entwicklerteams und Kunden über verschiedene Zeitzonen koordiniert.",
            "Verantwortlich für Backlog-Priorisierung, Projektumfang, Zeitpläne und funktionsübergreifende Kommunikation.",
          ],
        },
        {
          title: "Niederlassungsleiter / EdTech-Produktmanager",
          company: 'Computerakademie „STEP"',
          location: "Saporischschja, Ukraine",
          period: "Jul 2002 – Aug 2020",
          items: [
            "Strategie für Bildungs- und EdTech-Produkte geleitet – von der Lehrplanentwicklung bis zur Plattformbereitstellung.",
            "Partnerschaften mit Microsoft, Cisco und Autodesk für zertifizierte Lernmodule aufgebaut.",
            "Blended-Learning-Plattformen und ein CRM-basiertes System zur Nachverfolgung von Einschreibungen eingeführt.",
            "Verantwortlich für operative Abläufe und Prozesse im Bereich Unterrichtsdesign.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45 % Umsatzwachstum", detail: "Im Jahresvergleich durch Prozessoptimierung" },
        { icon: "👥", label: "75–125 Personen", detail: "Leitung bei unter 2 % Fluktuation" },
        { icon: "🚀", label: "10+ digitale Produkte", detail: "Erfolgreich in EdTech, SaaS und Energie" },
        { icon: "⚙️", label: "−30 % operative Ineffizienzen", detail: "Durch Automatisierung zentraler Prozesse" },
        { icon: "🔄", label: "Agile Transformation", detail: "In mehreren Abteilungen eingeführt" },
        { icon: "🤝", label: "Stakeholder-Vertrauen", detail: "Hohe Zufriedenheit und Kundenbindung" },
      ],
      skillGroups: [
        { title: "Projekt- & Produktmanagement", skills: ["Agile", "Scrum", "Kanban", "Wasserfall", "PLM", "MVP-Entwicklung", "Backlog-Pflege", "Anforderungserhebung", "Stakeholder-Management", "Risikomanagement", "Roadmapping", "OKRs", "KPIs", "Teamführung"] },
        { title: "PM-Tools", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Daten & Analytik", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Marketing & Automatisierung", skills: ["Google Ads", "Facebook Ads", "Zapier", "MailChimp", "GetResponse"] },
        { title: "Dokumentation & Kommunikation", skills: ["Microsoft Office", "Google Workspace", "Notion", "Confluence", "Miro", "Slack", "MS Teams"] },
        { title: "Technisches Grundwissen", skills: ["HTML/CSS", "JavaScript (Grundlagen)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Kommunikation mit Stakeholdern", "Teammoderation", "Konfliktlösung", "Strategisches Denken", "Datengestützte Entscheidungsfindung", "Priorisierung", "Roadmap-Planung", "Nutzerzentrierte Produktentwicklung", "Aktives Zuhören", "Zeit- und Ressourcenmanagement"],
    },

    ua: {
      title: "Проєктний менеджер | Продуктовий менеджер | Керівник бізнес- та IT-стратегії",
      summary: "Досвідчений проєктний та продуктовий менеджер із понад 20-річним досвідом в IT, освіті/EdTech та цифрових інноваціях. Керівництво міжфункціональними командами, успішний запуск цифрових продуктів та досягнення проєктних результатів відповідно до бізнес-цілей. Управління повним циклом продукту — від концепції та MVP до масштабування.",
      seeking: "Шукаю посаду проєктного або продуктового менеджера (Middle/Senior рівень) у динамічному середовищі з фокусом на IT-послуги, SaaS, AI, цифрову трансформацію або продуктові інновації. Готовий до роботи офіс/гібрид у NRW (район Дортмунда) або remote по всій Німеччині.",
      experience: [
        {
          title: "IT-директор",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Київ, Україна",
          period: "Вер 2023 – Січ 2024",
          items: [
            "Product Owner для B2B-платформи в сфері енергетичних технологій, перетворення бізнес-вимог на user stories.",
            "Визначення продуктової roadmap для платформи моніторингу та управління сонячними станціями.",
            "Співпраця з командами розробки для ітеративного постачання функціональних модулів.",
            "Забезпечення узгодженості зі стейкхолдерами та своєчасне постачання технічних рішень.",
          ],
        },
        {
          title: "Військовослужбовець",
          company: "Сили територіальної оборони (ТРО)",
          location: "Україна",
          period: "Лют 2022 – Вер 2023",
          items: [
            "Служба у силах ТРО Києва, внесок у національну безпеку в критичний період.",
            "Цінний досвід у дисципліні, командній роботі та антикризовому менеджменті.",
          ],
        },
        {
          title: "Операційний директор / Керівник проєктів",
          company: "IT-аутсорсингова компанія",
          location: "Таллінн, Естонія",
          period: "Лист 2013 – Груд 2023",
          items: [
            "Керівництво кількома міжнародними програмними проєктами від концепції до запуску.",
            "Побудова стандартизованих сервісних пропозицій та процесів постачання на базі Agile.",
            "Координація розподілених команд розробників і клієнтів у різних часових зонах.",
            "Пріоритизація беклогу, скоуп проєкту, терміни та міжфункціональна комунікація.",
          ],
        },
        {
          title: "Директор філії / EdTech-продуктовий менеджер",
          company: "Комп'ютерна академія «КРОК»",
          location: "Запоріжжя, Україна",
          period: "Лип 2002 – Серп 2020",
          items: [
            "Стратегія освітніх та EdTech-продуктів: від розробки навчальних програм до постачання платформ.",
            "Партнерства з Microsoft, Cisco, Autodesk для сертифікованих навчальних модулів.",
            "Впровадження платформ змішаного навчання та CRM-системи для відстеження зарахувань.",
            "Контроль операційних процесів та процесів інструкційного дизайну.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45% зростання доходу щорічно", detail: "Через оптимізацію процесів та масштабовану доставку" },
        { icon: "👥", label: "75–125 осіб", detail: "Керівництво командами з плинністю менш 2%" },
        { icon: "🚀", label: "10+ цифрових продуктів", detail: "Успішно в EdTech, SaaS та Energy" },
        { icon: "⚙️", label: "−30% операційних втрат", detail: "Через автоматизацію ключових процесів" },
        { icon: "🔄", label: "Agile-трансформація", detail: "Впроваджено в кількох підрозділах" },
        { icon: "🤝", label: "Довіра стейкхолдерів", detail: "Висока задоволеність і утримання клієнтів" },
      ],
      skillGroups: [
        { title: "Проєктний та продуктовий менеджмент", skills: ["Agile", "Scrum", "Kanban", "Waterfall", "PLM", "MVP-розробка", "Backlog Grooming", "Збір вимог", "Управління стейкхолдерами", "Управління ризиками", "Roadmapping", "OKRs", "KPIs", "Лідерство команди"] },
        { title: "Інструменти PM", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Дані та аналітика", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Маркетинг та автоматизація", skills: ["Google Ads", "Facebook Ads", "Zapier", "MailChimp", "GetResponse"] },
        { title: "Документація та комунікації", skills: ["Microsoft Office", "Google Workspace", "Notion", "Confluence", "Miro", "Slack", "MS Teams"] },
        { title: "Технічні основи", skills: ["HTML/CSS", "JavaScript (основи)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Комунікація зі стейкхолдерами", "Фасилітація команди", "Вирішення конфліктів", "Стратегічне мислення", "Рішення на основі даних", "Пріоритизація", "Планування roadmap", "Продуктова розробка з емпатією", "Активне слухання", "Управління часом та ресурсами"],
    },
  },

  coo: {
    en: {
      title: "C-Level Executive | CEO | COO | Business & IT Strategy Leader",
      summary: "Results-driven executive with 20+ years of experience in IT, EdTech, and digital transformation. Proven expertise in scaling businesses, optimizing operations, and driving profitability. Skilled in aligning technology with business strategy to maximize efficiency, revenue growth, and market expansion. Adept at leading cross-functional teams (125+ employees), managing multi-million-dollar budgets, and fostering innovation in fast-paced, high-growth environments.",
      seeking: "Seeking executive leadership C-Level roles where I can drive business transformation, optimize operations, and expand market reach. Open to opportunities in IT, digitalization, and international business sectors.",
      experience: [
        {
          title: "IT-Director",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Kyiv, Ukraine",
          period: "Sep 2023 – Jan 2024",
          items: [
            "Led IT strategy, overseeing network, security, and system architecture development.",
            "Managed software development projects for solar power plants, aligning IT with business objectives.",
            "Implemented data-driven solutions, optimizing efficiency and performance.",
          ],
        },
        {
          title: "Service Member",
          company: "Territorial Defense Forces (TRO)",
          location: "Ukraine",
          period: "Feb 2022 – Sep 2023",
          items: [
            "Served in the Kyiv Territorial Defense Forces, contributing to national security during a critical period.",
            "Gained valuable experience in discipline, teamwork, and crisis management.",
          ],
        },
        {
          title: "Chief Executive Officer",
          company: "IT Outsourcing Company",
          location: "Estonia",
          period: "Nov 2013 – Dec 2023",
          items: [
            "Developed and executed corporate growth strategies, driving revenue and profitability.",
            "Managed financial planning, budget allocation, and resource optimization.",
            "Led multi-site teams and remote operations, ensuring high performance and engagement.",
            "Formed and nurtured effective cross-functional teams.",
            "Built and optimized a system for managing business operations.",
          ],
        },
        {
          title: "Director of the Branch / COO",
          company: 'International IT Education "Computer Academy STEP"',
          location: "Zaporizhzhia, Ukraine",
          period: "Jul 2002 – Aug 2020",
          items: [
            "Built an effective operational framework, integrating digital learning platforms and automation tools.",
            "Spearheaded partnerships with Microsoft, Cisco, Autodesk, driving curriculum innovation.",
            "Developed and implemented the company's strategic growth plan.",
            "Implemented sustainable development systems; organized and supervised team performance.",
            "Improved business process efficiency; prepared reports, monitored contracts and financial discipline.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45% Revenue YoY", detail: "Over 3 years via strategic planning and process automation" },
        { icon: "💰", label: "28% → 55% Profitability", detail: "Through cost-effective strategies and operational optimization" },
        { icon: "🌍", label: "+20–25% Projects Annually", detail: "Expanded company market presence year over year" },
        { icon: "👥", label: "125+ Employees", detail: "Scaled teams with <4% turnover rate" },
        { icon: "🔄", label: "Digital Transformation", detail: "CRM, ERP, and cloud solutions streamlining operations" },
        { icon: "⚙️", label: "−30% Operational Inefficiencies", detail: "Through automation of key business processes" },
      ],
      skillGroups: [
        { title: "Core Competencies", skills: ["Business Strategy & Development", "P&L & Financial Management", "IT & Digital Transformation", "Process Automation", "Agile & Lean", "Stakeholder & Investor Relations", "Change Management", "Growth Scaling", "International Expansion", "Direct Sales", "Negotiation"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Project Management", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "Data & Analytics", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Infrastructure", skills: ["Windows/Mac OS/Linux", "Microsoft Server/AD", "VMWare", "VirtualBox", "OpenVPN"] },
        { title: "Technical Fundamentals", skills: ["HTML/CSS", "JavaScript (basics)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Strong Verbal & Written Communication", "Stakeholder & Investor Relations", "Team Leadership & Motivation", "Strategic Thinking", "Crisis Management", "Motivational Speaking", "Effective Presentations", "Active Listening"],
    },

    de: {
      title: "Führungskraft auf C-Level | Geschäftsführer (CEO/COO) | Experte für Geschäfts- und IT-Strategie",
      summary: "Ergebnisorientierte Führungskraft mit über 20 Jahren Erfahrung in IT, Bildungstechnologie (EdTech) und digitaler Transformation. Nachweisliche Erfolge beim Ausbau von Unternehmen, der Optimierung von Abläufen und der Steigerung der Rentabilität. Kompetent in der Führung von bereichsübergreifenden Teams (über 125 Mitarbeitende), im Umgang mit Millionenbudgets sowie in der Förderung von Innovationen.",
      seeking: "Ich suche eine Führungsposition auf C-Level, bei der ich Geschäftstransformation vorantreiben, Abläufe optimieren und Marktreichweite erweitern kann. Offen für Möglichkeiten in den Bereichen IT, Digitalisierung und internationales Geschäft.",
      experience: [
        {
          title: "IT-Direktor",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Kiew, Ukraine",
          period: "Sep 2023 – Jan 2024",
          items: [
            "IT-Strategie entwickelt, einschließlich Netzwerk, Sicherheit und Systemarchitektur.",
            "Softwareprojekte für Solarkraftwerke in Abstimmung mit den Unternehmenszielen geleitet.",
            "Datengestützte Lösungen zur Steigerung von Effizienz und Leistung eingeführt.",
          ],
        },
        {
          title: "Soldat",
          company: "Territorialverteidigungskräfte (TRO)",
          location: "Ukraine",
          period: "Feb 2022 – Sep 2023",
          items: [
            "In den Territorialverteidigungskräften von Kiew gedient und zur nationalen Sicherheit beigetragen.",
            "Wichtige Erfahrungen in Disziplin, Teamarbeit und Krisenmanagement gesammelt.",
          ],
        },
        {
          title: "Vorsitzender der Geschäftsführung (CEO)",
          company: "IT-Outsourcing-Unternehmen",
          location: "Estland",
          period: "Nov 2013 – Dez 2023",
          items: [
            "Wachstumsstrategien zur Steigerung von Umsatz und Gewinn entwickelt und umgesetzt.",
            "Finanzplanung, Budgetverteilung und optimale Nutzung der Ressourcen geplant.",
            "Teams an mehreren Standorten sowie Remote-Arbeit mit Fokus auf Leistung und Motivation geleitet.",
            "Effektive Teamarbeit aufgebaut und ein funktionierendes System zur Steuerung der Geschäftsabläufe etabliert.",
          ],
        },
        {
          title: "Niederlassungsleiter / Betriebsleiter (COO)",
          company: 'Internationale IT-Bildung „Computer Academy STEP"',
          location: "Saporischschja, Ukraine",
          period: "Jul 2002 – Aug 2020",
          items: [
            "Effektives Betriebsmodell mit digitalen Lernplattformen und Automatisierungstools aufgebaut.",
            "Partnerschaften mit Microsoft, Cisco, Autodesk zur Verbesserung des Lehrplans aufgebaut.",
            "Unternehmensstrategie entwickelt und umgesetzt, nachhaltige Entwicklungssysteme eingeführt.",
            "Effizienz und Qualität der Geschäftsprozesse laufend verbessert; Berichte erstellt und kontrolliert.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45 % Umsatz p.a.", detail: "Über 3 Jahre durch strategische Planung" },
        { icon: "💰", label: "28 % → 55 % Rentabilität", detail: "Durch kosteneffiziente Strategien" },
        { icon: "🌍", label: "+20–25 % Projekte p.a.", detail: "Marktpräsenz des Unternehmens erweitert" },
        { icon: "👥", label: "125+ Mitarbeitende", detail: "Teams mit unter 4 % Fluktuation geführt" },
        { icon: "🔄", label: "Digitale Transformation", detail: "CRM-, ERP- und Cloud-Lösungen eingeführt" },
        { icon: "⚙️", label: "−30 % operative Ineffizienzen", detail: "Durch Automatisierung zentraler Prozesse" },
      ],
      skillGroups: [
        { title: "Kernkompetenzen", skills: ["Geschäftsstrategie & -entwicklung", "P&L & Finanzmanagement", "IT & digitale Transformation", "Prozessautomatisierung", "Agile & Lean", "Stakeholder- & Investorenbeziehungen", "Change Management", "Wachstumsskalierung", "Internationale Expansion", "Direktvertrieb", "Verhandlungsführung"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Projektmanagement", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "Daten & Analysen", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Infrastruktur", skills: ["Windows/Mac OS/Linux", "Microsoft Server/AD", "VMWare", "VirtualBox", "OpenVPN"] },
        { title: "Technisches Grundwissen", skills: ["HTML/CSS", "JavaScript (Grundlagen)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Starke mündliche & schriftliche Kommunikation", "Stakeholder- & Investorenbeziehungen", "Teamführung & Motivation", "Strategisches Denken", "Krisenmanagement", "Motivationsredner", "Effektive Präsentationen", "Aktives Zuhören"],
    },

    ua: {
      title: "Керівник вищої ланки | CEO | COO | Керівник бізнес- та IT-стратегії",
      summary: "Результативний керівник із понад 20-річним досвідом у сферах ІТ, EdTech та цифрової трансформації. Підтверджена експертиза у масштабуванні бізнесу, оптимізації операційної діяльності та забезпеченні прибутковості. Досвід керівництва міжфункціональними командами (понад 125 працівників), управління багатомільйонними бюджетами та впровадження інновацій.",
      seeking: "Шукаю керівну посаду на рівні C-Level, де зможу забезпечити трансформацію бізнесу, оптимізацію операційних процесів та розширення ринкової присутності. Відкритий до можливостей у сферах ІТ, цифровізації та міжнародного бізнесу.",
      experience: [
        {
          title: "IT-директор",
          company: "Keyvolt",
          companyUrl: "https://keyvolt.com",
          location: "Київ, Україна",
          period: "Вер 2023 – Січ 2024",
          items: [
            "Керування ІТ-стратегією, контроль розробки мережі, безпеки та системної архітектури.",
            "Управління проєктами розробки ПЗ для сонячних електростанцій, узгодження ІТ з бізнес-цілями.",
            "Впровадження рішень на основі даних, оптимізація ефективності та продуктивності.",
          ],
        },
        {
          title: "Військовослужбовець",
          company: "Сили територіальної оборони (ТРО)",
          location: "Київ, Україна",
          period: "Лют 2022 – Вер 2023",
          items: [
            "Служба у силах ТРО, внесок у національну безпеку та оборону у критичний період вторгнення.",
            "Цінний досвід у дисципліні, командній роботі та антикризовому менеджменті.",
          ],
        },
        {
          title: "Операційний директор (CEO)",
          company: "IT-аутсорсингова компанія",
          location: "Естонія",
          period: "Лист 2013 – Груд 2023",
          items: [
            "Розробка та впровадження стратегій корпоративного зростання, збільшення доходів та прибутковості.",
            "Управління фінансовим плануванням, розподілом бюджету та оптимізацією ресурсів.",
            "Керування командами на кількох об'єктах та віддаленими операціями.",
            "Формування та виховання ефективних крос-функціональних команд.",
            "Побудова та оптимізація системи управління бізнес-операціями.",
          ],
        },
        {
          title: "Директор філії / COO",
          company: "Міжнародна IT-освіта «Комп'ютерна академія КРОК»",
          location: "Запоріжжя, Україна",
          period: "Лип 2002 – Серп 2020",
          items: [
            "Розробка ефективної операційної моделі, інтеграція цифрових навчальних платформ та автоматизації.",
            "Партнерства з Microsoft, Cisco, Autodesk, оновлення навчальних програм.",
            "Розробка і реалізація стратегічного плану зростання компанії.",
            "Підвищення ефективності бізнес-процесів; звітність, контроль договорів та фінансової дисципліни.",
          ],
        },
      ],
      achievements: [
        { icon: "📈", label: "+45% доходу щорічно", detail: "Протягом 3 років через стратегічне планування" },
        { icon: "💰", label: "28% → 55% прибутковість", detail: "Через економічно ефективні стратегії" },
        { icon: "🌍", label: "+20–25% проєктів щорічно", detail: "Розширення ринкової присутності" },
        { icon: "👥", label: "125+ працівників", detail: "Команди з плинністю менш 4%" },
        { icon: "🔄", label: "Цифрова трансформація", detail: "CRM, ERP та хмарні рішення" },
        { icon: "⚙️", label: "−30% операційних втрат", detail: "Автоматизація ключових процесів" },
      ],
      skillGroups: [
        { title: "Ключові компетенції", skills: ["Стратегія та розвиток бізнесу", "P&L та фінансовий менеджмент", "ІТ та цифрова трансформація", "Автоматизація процесів", "Agile та Lean", "Відносини зі стейкхолдерами та інвесторами", "Change Management", "Масштабування зростання", "Міжнародна експансія", "Прямі продажі", "Переговори"] },
        { title: "CRM & ERP", skills: ["Zoho", "HubSpot", "HubStaff", "Hurma", "PeopleForce"] },
        { title: "Управління проєктами", skills: ["Jira", "Trello", "Asana", "PipeDrive", "Monday.com"] },
        { title: "Дані та аналітика", skills: ["Google Analytics", "Microsoft Clarity", "Power BI"] },
        { title: "Інфраструктура", skills: ["Windows/Mac OS/Linux", "Microsoft Server/AD", "VMWare", "VirtualBox", "OpenVPN"] },
        { title: "Технічні основи", skills: ["HTML/CSS", "JavaScript (основи)", "SQL/NoSQL", "SDLC"] },
      ],
      softSkills: ["Сильна усна та письмова комунікація", "Відносини зі стейкхолдерами та інвесторами", "Лідерство та мотивація команди", "Стратегічне мислення", "Антикризовий менеджмент", "Мотиваційний спікер", "Ефективні презентації", "Активне слухання"],
    },
  },

  ui: {
    en: {
      position: "Position", pm: "Project Manager", coo: "CEO / COO",
      experience: "Experience", achievements: "Key Achievements",
      skills: "Skills & Tools", softSkills: "Soft Skills",
      languages: "Languages", education: "Education",
      seeking: "About", print: "Print / Save PDF",
    },
    de: {
      position: "Position", pm: "Projektmanager", coo: "CEO / COO",
      experience: "Berufserfahrung", achievements: "Wichtige Erfolge",
      skills: "Fähigkeiten & Tools", softSkills: "Soft Skills",
      languages: "Sprachkenntnisse", education: "Ausbildung",
      seeking: "Über mich", print: "Drucken / PDF speichern",
    },
    ua: {
      position: "Позиція", pm: "Проєктний менеджер", coo: "CEO / COO",
      experience: "Досвід роботи", achievements: "Ключові досягнення",
      skills: "Навички та інструменти", softSkills: "Soft Skills",
      languages: "Мовні навички", education: "Освіта",
      seeking: "Про мене", print: "Друк / Зберегти PDF",
    },
  },
};
